In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
import seaborn as sns

In [6]:
df=pd.read_csv("iris.csv")

In [7]:
df                                                

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [9]:
l=["sepal.length","sepal.width","petal.length","petal.width"]

In [10]:
x=df[l]
y=df["variety"]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=10)

In [13]:
from sklearn.svm import SVC

In [14]:
a=SVC()

In [15]:
a.fit(x_train,y_train)

SVC()

In [16]:
pre=a.predict(x_test)

In [17]:
pre

array(['Versicolor', 'Virginica', 'Setosa', 'Versicolor', 'Setosa',
       'Versicolor', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Versicolor', 'Setosa', 'Setosa',
       'Virginica', 'Versicolor', 'Setosa', 'Setosa', 'Setosa',
       'Virginica', 'Virginica', 'Virginica', 'Setosa', 'Versicolor',
       'Setosa', 'Versicolor', 'Versicolor', 'Versicolor', 'Virginica'],
      dtype=object)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [19]:
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      0.92      0.96        13
   Virginica       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [20]:
print(accuracy_score(y_test,pre))

0.9666666666666667


In [21]:
print(confusion_matrix(y_test,pre))

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]


In [22]:
a.support_vectors_

array([[4.5, 2.3, 1.3, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3. , 1.6, 0.2],
       [6.6, 2.9, 4.6, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [6.2, 2.2, 4.5, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [5.1, 2.5, 3. , 1.1],
       [6. , 2.7, 5.1, 1.6],
       [5.7, 2.6, 3.5, 1. ],
       [7. , 3.2, 4.7, 1.4],
       [5.7, 2.9, 4.2, 1.3],
       [5.4, 3. , 4.5, 1.5],
       [6.6, 3. , 4.4, 1.4],
       [5.6, 2.7, 4.2, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 2.4, 3.3, 1. ],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3. , 5. , 1.7],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [5.6, 2.9, 3.6, 1.3],
       [7.2, 3. , 5.8, 1.6],
       [6.3, 2.5, 5. , 1.9],
       [6.9, 3.1, 5.1, 2.3],
       [5.6, 2

In [23]:
a.n_support_

array([ 6, 25, 21])