In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
import seaborn as sns

In [2]:
df=pd.read_csv("iris.csv")

In [4]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
l=["sepal.length","sepal.width","petal.length","petal.width"]

In [8]:
x=df[l]
y=df["variety"]

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=10)

In [14]:
from sklearn.decomposition import PCA

In [16]:
P = PCA(n_components=1)

In [17]:
A = P.fit_transform(x_train)

In [18]:
B = P.transform(x_test)

In [19]:
x_train

sepal.length  sepal.width  petal.length  petal.width
58            6.6          2.9           4.6          1.3
97            6.2          2.9           4.3          1.3
129           7.2          3.0           5.8          1.6
114           5.8          2.8           5.1          2.4
146           6.3          2.5           5.0          1.9
..            ...          ...           ...          ...
113           5.7          2.5           5.0          2.0
64            5.6          2.9           3.6          1.3
15            5.7          4.4           1.5          0.4
125           7.2          3.2           6.0          1.8
9             4.9          3.1           1.5          0.1

[120 rows x 4 columns]

In [20]:
x_test

sepal.length  sepal.width  petal.length  petal.width
87            6.3          2.3           4.4          1.3
111           6.4          2.7           5.3          1.9
10            5.4          3.7           1.5          0.2
91            6.1          3.0           4.6          1.4
49            5.0          3.3           1.4          0.2
60            5.0          2.0           3.5          1.0
72            6.3          2.5           4.9          1.5
67            5.8          2.7           4.1          1.0
39            5.1          3.4           1.5          0.2
55            5.7          2.8           4.5          1.3
66            5.6          3.0           4.5          1.5
142           5.8          2.7           5.1          1.9
53            5.5          2.3           4.0          1.3
1             4.9          3.0           1.4          0.2
19            5.1          3.8           1.5          0.3
112           6.8          3.0           5.5          2.1
85            6.0          3.4           4.5          1.6
38            4.4          3.0           1.3          0.2
21            5.1          3.7           1.5          0.4
35            5.0          3.2           1.2          0.2
102           7.1          3.0           5.9          2.1
132           6.4          2.8           5.6          2.2
126           6.2          2.8           4.8          1.8
24            4.8          3.4           1.9          0.2
61            5.9          3.0           4.2          1.5
2             4.7          3.2           1.3          0.2
95            5.7          3.0           4.2          1.2
90            5.5          2.6           4.4          1.2
76            6.8          2.8           4.8          1.4
117           7.7          3.8           6.7          2.2

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
k=KNeighborsClassifier(n_neighbors=15)

In [34]:
k.fit(A,y_train)

KNeighborsClassifier(n_neighbors=15)

In [35]:
pre=k.predict(B)

In [36]:
pre

array(['Versicolor', 'Virginica', 'Setosa', 'Versicolor', 'Setosa',
       'Versicolor', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Versicolor', 'Setosa', 'Setosa',
       'Virginica', 'Versicolor', 'Setosa', 'Setosa', 'Setosa',
       'Virginica', 'Virginica', 'Virginica', 'Setosa', 'Versicolor',
       'Setosa', 'Versicolor', 'Versicolor', 'Virginica', 'Virginica'],
      dtype=object)

In [37]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [38]:
print(classification_report(y_test,pre))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      0.85      0.92        13
   Virginica       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.93        30
weighted avg       0.95      0.93      0.93        30



In [39]:
print(confusion_matrix(y_test,pre))

[[10  0  0]
 [ 0 11  2]
 [ 0  0  7]]


In [40]:
print(accuracy_score(y_test,pre))

0.9333333333333333
